name: ESLint

on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Install dependencies & lint
    steps:
      - uses: actions/checkout@v1
      - run: yarn
      - uses: actions/checkout@v1
      - uses: a-b-r-o-w-n/eslint-action@v1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          files: "src/**/*"
          extensions: ".js,.ts"
