name: ESLint

on: [pull_request, push]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "12.0.0"
          yarn-version: "1.9.4"
      - uses: actions/checkout@v1
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test # will run `yarn test` command
      # - uses: a-b-r-o-w-n/eslint-action@v1
      #   with:
      #     repo-token: "${{ secrets.GITHUB_TOKEN }}"
      #     files: "src/**/*"
      #     extensions: ".js,.ts"
