name: CI

on:
  push:
    branches:
    - master
    - development
    - feature/*
    - bugfix/*
    - enhancement/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: eslint
    - uses: reviewdog/action-eslint@v1
      with:
        github_token: ${{ secrets.github_token }}
        reporter: portad
        eslint_flags: 'src/'
