name: CI

on:
  push:
    branches:
    - master
    - development
    - feature/*
    - bugfix/*
    - enhancement/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: ESLint Action
      uses: hallee/eslint-action@1.0.1
